### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vbashiri** [spheenik/clarity-analyzer#9]
I build clarity-analyzer on mac with java 1.8.0_201 and maven 3.6.1.

the errors are

> Error:(29,57) java: cannot find symbol

wich is for 

`List<FieldPath> fieldPaths = entity.getDtClass().collectFieldPaths(entity.getState());`

collectFieldPaths cannot be resolved.

and

> Error:(54,27) java: no suitable method found for binarySearch(java.util.List<skadistats.clarity.model.FieldPath>,skadistats.clarity.model.FieldPath)

which is for line 

`public int getIndexForFieldPath(FieldPath fieldPath) {
        return Collections.binarySearch(indices, fieldPath);
    }`

sorry if I miss anything, I am new. :D

**Comment by spheenik** [comment]
Hmm, I probably forgot to deploy a new snapshot for clarity 2.5.
I just did. 
Can you try again?

**Comment by Oibaf94** [comment]
hi, i tried building this on windows 10 with java 1.8.0_131 and maven 3.6.2 and i get these same 2 errors

![Screenshot_1](https://user-images.githubusercontent.com/30326333/64881526-45a01d80-d65b-11e9-8d4c-f657378378f8.png)

**Comment by spheenik** [comment]
Forgot to push some commits. Sorry. Should work now.

**Comment by Oibaf94** [comment]
actually i still get the same exact errors.
 i'm not sure if i'm missing something tbh.
 I managed to make the project compile by commenting out every line that was giving errors, but then when i go into a replay i get empty tables for every entity so it obviously breaks something important.
was i supposed to actually do something to get those commits you pushed? asking cause i'm not too familiar with how github works, sorry for the trouble

**Comment by spheenik** [comment]
You got to pull the changes, did you?

**Comment by Oibaf94** [comment]
the changes i made on my end to make it compile break the whole thing so no point to request a pull.
actually i think its possible that the commits you pushed didn't go trough/didn't update? 
I tried going here https://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity/2.5-SNAPSHOT/
and the last change to clarity-2.5-20190904.064646-5.jar where my compiler says the issue is is from the 4th of september.

I also couldn't find the collectFieldPaths method anywhere in EntityState.class which i assume is where it's supposed to be?

I'm not that good of a programmer so i'm kinda taking a shot in the dark, i'd try to fix it myself but i have no clue on earth how to do that. 
sorry again for taking your time

**Comment by spheenik** [comment]
No, you misunderstood. I do not want a pull request, I want you to pull the changes I made to clarity-analyzer this morning.
Just erase the repo and clone again if you do not know how.

**Comment by Oibaf94** [comment]
oh, yeah sorry, it works now.
I thought that since in the github page it showed no recent update that there wasn't any change from what i cloned just yesterday. 
Thanks a lot, amazing work

**Comment by vbashiri** [comment]
I pull the changes and now everything works perfectly. Just another question, Is there any way to turn on fog of war? Is such a data send by server in the first place or does the clarity parse these kinds of information?

and thank you for your great work, feel free to close the issue.

**Comment by spheenik** [comment]
The replay is written from the server's perspective, so it contains all entities per se. There is a flag on every entity (something named "visibleByTeam" or so), which you could use. The actual fog information, for example obstruction from trees etc. is not encoded in the replay, but calculated by the client in real time.

**Comment by vbashiri** [comment]
thank you very much. :7
